# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be0dcffc425d037ff030678ab449f2f0ea05d994fb5d37e1acc75df7ddd95166f8026a9c0136a70287d11d1f1041e8d69b2d1abbf42ccc32d68bce50d681fef4
  github_key: <%=ENV['GITHUB_KEY']%>
  github_secret: <%=ENV['GITHUB_SECRET']%>
  github_owner: <%=ENV['GITHUB_OWNER']%>

test:
  secret_key_base: 026ba28adb2f327b4266ab1131298be4cda9f00c1f95889b6e7125dbe5a8760aa580c7102e9d61f485cc76cf9513f17e01fcc1310258652bfa77f92970c89b29
  github_key:
  github_secret:
  github_owner:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%=ENV["SECRET_KEY"]%>
  github_key: <%=ENV['GITHUB_KEY']%>
  github_secret: <%=ENV['GITHUB_SECRET']%>
  github_owner: <%=ENV['GITHUB_OWNER']%>
